using System.Collections.Generic;
using UnityEngine;

public class LobbyNames : MonoBehaviour
{
    public List<string> questNames;

    internal string getRandomName()
    {
        Debug.Log(questNames[Random.Range(0, questNames.Count)]);
        return questNames[Random.Range(0, questNames.Count)];
    }

    // Names generated by openAI's chatGPT https://chat.openai.com/chat
    void Start()
    {
        questNames = new List<string>
        {
            "Forbidden Treasures",
            "Eternal Flames",
            "Mystic Stones",
            "Frosty Summit",
            "Lost Artifacts",
            "Hidden Tomes",
            "Whispering Woods",
            "Enchanted Realms",
            "Haunted Ruins",
            "Cursed Crypts",
            "Shrouded Isles",
            "Savage Lands",
            "Forgotten Temples",
            "Ancient Relics",
            "Bewitched Labyrinth",
            "Dragon's Hoard",
            "Pirate's Bounty",
            "Deadly Venom",
            "Giant's Strength",
            "Goblin's Mischief",
            "Siren's Song",
            "Troll's Bane",
            "Phoenix Rising",
            "Orcish Ambush",
            "Bandit's Lair",
            "Undead Menace",
            "Wraith's Curse",
            "Wyvern's Roost",
            "Mermaid's Kiss",
            "Centaur's Glory",
            "Griffin's Flight",
            "Minotaur's Maze",
            "Chimera's Fury",
            "Basilisk's Gaze",
            "Kraken's Wake",
            "Gorgon's Stare",
            "Cerberus' Gates",
            "Hydra's Heads",
            "Manticore's Hunt",
            "Necromancer's Plague",
            "Vampire's Den",
            "Werewolf's Curse",
            "Demon's Pact",
            "Angel's Grace",
            "Divine Intervention",
            "Cosmic Conflict",
            "Ethereal Trials",
            "Celestial Wonders",
            "Otherworldly Quests",
            "Mythical Adventures",
            "Legendary Feats"
        };
    }
}